### ISSUE TITLE
Add a http://physiomodel.org dns entry

### ISSUE THREAD

**Issue by dietmarw** [physiology/Physiomodel#3]
Having to type www in front of any address is outdated. Nowadays it is common to have either the main URL directly, e.g., http://physiomodel.org or simply a redirect to http://www.physiomodel.org

**Comment by MarekMatejak** [comment]
Does it work yet? I am not sure, whether it is a function of my browsers or DNS.

**Comment by dietmarw** [comment]
Yes it works :+1:
